service: custom-lambda-zork

provider:
  name: aws
  region: us-west-2
#  architecture: arm64
  ecr:
    images:
      aws-custom-container:
        path: ./

functions:
  test:
    image:
      name: custom-lambda-zork